FitxProsjekt/urls.py
from django.contrib import admin
from django.urls import path, include

from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Calories.url')),
    path('', include('accounts.url')),
    path('', include('boards.url')),
    path('', include('workouPlan.url')),
]

boards/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import Truncator
# Create your models here.


class Board(models.Model):
    name = models.CharField(max_length=50,unique=True)
    description = models.CharField(max_length=150)

    def __str__(self):
        return self.name

  #  def get_posts_count(self):
   #     return Post.objects.filter(topic__board=self).count()

    #def get_last_post(self):
     #   return Post.objects.filter(topic__board=self).order_by('-created_dt').first()


class Topic(models.Model):
    subject = models.CharField(max_length=255)
    board = models.ForeignKey(Board,related_name='topics',on_delete=models.CASCADE)
    created_by = models.ForeignKey(User,related_name='topics',on_delete=models.CASCADE)
    created_dt = models.DateTimeField(auto_now_add=True)
    views = models.PositiveIntegerField(default=0)
    updated_by = models.ForeignKey(User,null=True,related_name='+',on_delete=models.CASCADE)
    updated_dt = models.DateTimeField(null=True)

    def __str__(self):
        return self.subject

class Post(models.Model):
    message = models.TextField(max_length=4000)
    topic = models.ForeignKey(Topic,related_name='posts',on_delete=models.CASCADE)
    created_by = models.ForeignKey(User,related_name='posts',on_delete=models.CASCADE)
    created_dt = models.DateTimeField(auto_now_add=True)
    updated_by = models.ForeignKey(User,null=True,related_name='+',on_delete=models.CASCADE)
    updated_dt = models.DateTimeField(null=True)
    def __str__(self):
        truncted_message = Truncator(self.message)
        return truncted_message.chars(30)

boards/forms.py
from django import forms
from .models import Topic , Post

class NewTopicForm(forms.ModelForm):

    message = forms.CharField(widget=forms.Textarea(
        attrs={'rows':5,'placeholder':'What is on your mind?'}
    ),
    max_length=4000,
    help_text='The max length of the text is 4000')

    class Meta:
        model = Topic
        fields = ['subject','message']


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['message',]

boards/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, redirect

from .forms import NewTopicForm
from .models import Board, Topic, Post


# Create your views here.

def boards(request):
    boards = Board.objects.all()
    return render(request,'boards.html',{'boards':boards})


def board_topics(request, board_id):
    board= get_object_or_404(Board, pk=board_id)
    return render(request,'topics.html',{'board':board})

def new_topic(request, board_id):
    board = get_object_or_404(Board, pk=board_id)
    form = NewTopicForm()
    #if request.method=='POST':
    #subject = request.POST['subject']
      # user = User.objects.first()
       # topic = Topic.objects.create(
        #    subject=subject,
         #   board=board,
         #   created_by=user
        #)
        #post = Post.objects.create(
        #    message=message,
        #     topic=topic,
        #    created_by=user
        #)
        #return redirect('board_topics', board_id=board.pk)
    return render(request, 'new_topic.html',{'board':board,'form':form})

#def p (request, board_id):
 #   board = get_object_or_404(Board, pk=board_id)
  #  return redirect('board_topics', board_id=board.pk)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <script src=
      "https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src=
      "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src=
      "https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light  ">
      <a class="navbar-brand" href="#">  <img src=""> </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      {%if user.is_authenticated%}
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0 ">
        <li class="nav-item">
          <a class="nav-link" href="#">Matplan</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'val'  %}">trenningsplan</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Blog</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home'  %}">Kalori Kalkolator</a>
        </li>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Hi, welcom back {{ user.username}}!!</a>
        </li>
      </ul>
      <a href={% url 'logout' %}>Log out</a>
      {% else %}
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0 ">
          <li class="nav-item">
            <a class="nav-link" href="#">Matplan</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" >trenningsplan</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'boards'  %}">Blog</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home'  %}">Kalori Kalkolator</a>
          </li>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Welcome, login or signup</a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'user_register'  %}">sign up</a>
          </li>
          <li class="nav-item ">
            <a class="nav-link navbar-nav" href="{% url 'login' %}">Log in</a>
          </li>
        </ul>
        {% endif %}
      </div>
    </nav>
    {% block content %}
    {% endblock %}
    <!-- Site footer -->
    <footer class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-6">
            <h6>About</h6>
            <p class="text-justify">Scanfcode.com <i>CODE WANTS TO BE SIMPLE </i> is an initiative  to help the upcoming programmers with the code. Scanfcode focuses on providing the most efficient code or snippets as the code wants to be simple. We will help programmers build up concepts in different programming languages that include C, C++, Java, HTML, CSS, Bootstrap, JavaScript, PHP, Android, SQL and Algorithm.</p>
          </div>
          <div class="col-xs-6 col-md-3">
            <h6>Categories</h6>
            <ul class="footer-links">
              <li><a href="#">C</a></li>
              <li><a href="#">UI Design</a></li>
              <li><a href="#">PHP</a></li>
              <li><a href="#">Java</a></li>
              <li><a href="#">Android</a></li>
              <li><a href="#">Templates</a></li>
            </ul>
          </div>
          <div class="col-xs-6 col-md-3">
            <h6>Quick Links</h6>
            <ul class="footer-links">
              <li><a href="#">About Us</a></li>
              <li><a href="#">Contact Us</a></li>
              <li><a href="#">Contribute</a></li>
              <li><a href="#">Privacy Policy</a></li>
              <li><a href="#">Sitemap</a></li>
            </ul>
          </div>
        </div>
        <hr>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-sm-6 col-xs-12">
            <p class="copyright-text">Copyright &copy; 2017 All Rights Reserved by
              <a href="#">Scanfcode</a>.
            </p>
          </div>
          <div class="col-md-4 col-sm-6 col-xs-12">
            <ul class="social-icons">
              <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a class="dribbble" href="#"><i class="fa fa-dribbble"></i></a></li>
              <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

templates/boards.html
{% extends 'base.html' %}
{% load static %}
 <link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}">
{% block content %}
<table class="table">
    <thead class="thead-dark">
    <tr>
        <th>Board</th>
        <th>Posts</th>
        <th>Topic</th>
        <th>Last Post</th>
    </tr>
    </thead>
    <tbody>
    {% for board in boards%}
    <tr>
        <td><a href="{% url 'board_topics' board.pk  %}">{{ board.name }} </a>
        <small class="text-muted d-block">{{board.description}}</small>
        </td>
        <td>{{board.get_posts_count}}</td>  <!-- viktig å komme tilbake til den-->
        <td>{{board.topics.count}}</td>
    </tr>
    {%endfor%}

    </tbody>
</table>

{%endblock%}

templates/home.html
{% extends 'base.html' %}
{% load static %}

    {% block content %}
        <link rel="stylesheet" href="{% static 'css/home.css' %}">

    <div class="bgimg">
      <div class="middle">
        <h1>COMING SOON</h1>
        <hr>
        <p>35 days left</p>
      </div>
      <div class="bottomleft">
        <p>Big Things is happening wallah bror <br> Lorem Ipsum is simply dummy text of
          the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy
          text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a
          type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting,
          remaining essentially unchanged.
        </p>
      </div>
    </div>
    {% endblock %}

templates/kalori.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<head>
  <link rel="stylesheet" href="{% static 'css/kalori.css' %}">
  <script src="{% static 'js/kalori.js' %}"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta http-equiv="x-ua-compatible" content="ie=edge" />
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Google Fonts Roboto -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
</head>
<body>
  <header>
    <nav class="navbar navbar-dark orange">
      <span
        style="color: white; font-size: 23px; font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;"><i
        class="fas fa-calculator"></i> Calorie Calculator</span>
    </nav>
  </header>
  <main>
    <p class="text-center font-weight-bold" style="margin-top: 25px; font-size: large;">Insert your data below to calculate your recommended calories intake!</p>
    <div class="card text-center border-warning-color-dark"
      style="max-width: 50rem; margin: auto; border: 3px solid orange; width: 50%; margin-top: 30px; min-width: 20rem;">
      <table class="table" style="border-spacing: 0rem;">
        <form>
          <tr>
            <td class="T">Gender</td>
            <td class="I">
              <input type="radio" name="gender" value="male" id="male" checked="checked"> Male &nbsp &nbsp
              <input type="radio" name="gender" value="female" id="female"> Female
            </td>
          </tr>
          <tr>
            <td class="T">Age</td>
            <td class="I" id="AT">
              <input type="number" min="0" id="age" placeholder=""
                style="border-width: 2px; border-color: rgb(255, 123, 0); border-radius: 5px;">
              <div style="display: none;" id="ATT">Please enter valid number</div>
            </td>
          </tr>
          <tr>
            <td class="T">Weight</td>
            <td class="I">
              <input type="number" min="0" id="weight"
                style="border-width: 2px; border-color: rgb(255, 123, 0); border-radius: 5px;" placeholder="Kg">
              <div style="display: none;" id="WTT">Please enter valid number</div>
            </td>
          </tr>
          <tr>
            <td class="T">Height</td>
            <td class="I">
              <input type="number" min="0" id="height"
                style="border-width: 2px; border-color: rgb(255, 123, 0); border-radius: 5px;" placeholder="Cm">
              <div style="display: none;" id="HTT">Please enter valid number</div>
            </td>
          </tr>
        </form>
        <tr>
          <td class="T">
            Exercise level
            <p>/Activity</p>
          </td>
          <td>
            <select class="custom-select custom-select-sm"
              style="width: 70%; margin: auto; border-width: 2px; border-color: rgb(255, 123, 0); border-radius: 5px; margin-top: 12px;">
              <!--KONO DIO DA -->
              <option value="0" id="0">Basal Metabolic Rate (BMR)</option>
              <option value="1" id="1">Little/No exercise</option>
              <option value="2" id="2">Low activity (exercise 1-3 times/week)</option>
              <option value="3" id="3">Active (daily exercise or intense exercise 3-4 times/week)</option>
              <option value="4" id="4">High activity (intense exercise 6-7 times/week)</option>
              <option value="5" id="5">Very high activity (very intense exercise daily, or physical job)</option>
            </select>
          </td>
        </tr>
      </table>
      <!-- UwU -->
      <button id="B" type="button" onclick="calc()" class="btn btn-amber"
        style="width: 300px; margin: auto; margin-bottom: 25px; border-radius: 25px;">Calculate</button>
    </div>
    <!-- Score -->
    <div id="Final" class="card text-center"
      style="max-width: 25rem; margin: auto; border: 6px solid orange; width: 50%; margin-top: 45px; background-color:#fff176; border-radius: 20px; color:#ff6d00; display: none; margin-bottom: 30px">
      <table style="margin-top: 15px;">
        <tr>
          <td class="T" style="font-weight: bold;">
            Maintain weight
            <p></p>
          </td>
          <td>
            <div id="a" class="SS">&nbsp</div>
            <div class="CD">Calories/day</div>
          </td>
        </tr>
        <tr>
          <td class="T" style="font-weight: bold;">
            Weight loss
            <p
              style="font-size: small; color:#888; font-weight: lighter;">0.5 kg/week</p>
          </td>
          <td>
            <div id="b" class="SS">&nbsp</div>
            <div class="CD">Calories/day</div>
          </td>
        </tr>
        <tr>
          <td class="T" style="font-weight: bold;">
            Weight gain
            <p
              style="font-size: small; color:#888; font-weight: lighter;">0.5 kg/week</p>
          </td>
          <td>
            <div id="c" class="SS">&nbsp</div>
            <div class="CD">Calories/day</div>
          </td>
        </tr>
      </table>
         <button type="button" class="btn btn-amber"
        style="width: 300px; margin: auto; margin-bottom: 25px; border-radius: 25px;">Sjekk Vår MatList</button>
    </div>
  </main>
</body>
</html>
{% endblock %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
         <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>
 <div class="container">
        <form method="post">
            {% csrf_token %}
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Login</div>
                    <div class="panel-body">
                        {% if error_message %}
                            <p class="bg-danger p-d ml-b">{{ error_message }}</p>
                        {% endif %}
                        <div class="form-group clearfix">
                            <label for="username" class="col-md-4 control-label text-right">Username:</label>
                            <div class="col-md-6">
                                <input name="username" value="" type="text" class="form-control" />
                            </div>
                        </div>
                        <div class="form-group clearfix">
                            <label for="password" class="col-md-4 control-label text-right">Password:</label>
                            <div class="col-md-6">
                                <input name="password" type="password" class="form-control" />
                            </div>
                        </div>
                        <div class="col-md-6 col-md-offset-4">
                            <input name="login" type="submit" value="Login" class="btn btn-success" /> &nbsp;
                            <a href="{% url 'user_register'  %}">or Register</a>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>

</body>
</html>

templates/new_topic.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}">
    <meta charset="UTF-8">
    <title>Create New Topic</title>
</head>
<body>
<div class="container">
    <ol class="breadcrumb my-4">
        <li class="breadcrumb-item"><a href="{% url 'boards'%}"> Boards </a></li>
        <li class="breadcrumb-item "><a href="{% url 'board_topics' board.pk %}">{{ board.name }}</a></li>
          <li class="breadcrumb-item active ">New Topic</li>

    </ol>
</div>
<form method="post">
    {%csrf_token%}

    {{form.as_p}}



    <!--  <div class="form-group">
    <label>Subject</label>
    <input type="text" name="subject" id="id_subject">
    </div>
    <div class="form-group">
    <label>Message</label>
    <textarea name="message" id="id_message"  rows="5"></textarea>
    </div>
    -->
    <button type="submit" class="btn btn-success">Add</button>
</form>
</body>
</html>

templates/signup.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

</head>
<body>
        <a class="nav-link" href="{% url 'khara'%}">Back to home page</a>

<div class="container">
        <form method="post">
            {% csrf_token %}
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Register</div>
                    <div class="panel-body">
                        {% if error_message %}
                            <p class="bg-danger p-d ml-b">{{ error_message }}</p>
                        {% endif %}

                        <div class="form-group clearfix">
                            <label for="{{ form.username.id_for_label }}" class="col-md-4 control-label text-right">Username<span class="text-red">*</span>:</label>
                            <div class="col-md-6">
                                {{ form.username }}
                            </div>
                        </div>
                        <div class="form-group clearfix">
                            <label for="{{ form.email.id_for_label }}" class="col-md-4 control-label text-right">Email<span class="text-red">*</span>:</label>
                            <div class="col-md-6">
                                {{ form.email }}
                            </div>
                        </div>
                        <div class="form-group clearfix">
                            <label for="{{ form.password.id_for_label }}" class="col-md-4 control-label text-right">Password<span class="text-red">*</span>:</label>
                            <div class="col-md-6">
                                {{ form.password }}
                            </div>
                        </div>
                        <div class="form-group clearfix">
                            <label for="{{ form.password_repeat.id_for_label }}" class="col-md-4 control-label text-right">Confirm password:</label>
                            <div class="col-md-6">
                                {{ form.password_repeat }}
                            </div>
                        </div>
                        <div class="form-group clearfix">
                            <label for="{{ form.first_name.id_for_label }}" class="col-md-4 control-label text-right">First Name:</label>
                            <div class="col-md-6">
                                {{ form.first_name }}
                            </div>
                        </div>
                        <div class="form-group clearfix">
                            <label for="{{ form.last_name.id_for_label }}" class="col-md-4 control-label text-right">Last Name:</label>
                            <div class="col-md-6">
                                {{ form.last_name }}
                            </div>
                        </div>

                        <div class="col-md-6 col-md-offset-4">
                            <input type="submit" value="Register" class="btn btn-success">
                        </div>
                    </div>
                </div>
            </div>
        </form>
</div>
            </body>
</html>

templates/topics.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}">
    <meta charset="UTF-8">
    <title>{{ board.name }}</title>
</head>
<body>
<div class="container">
    <ol class="breadcrumb my-4">
        <li class="breadcrumb-item shadow alert-info"><a href="{% url 'boards'%}"> Boards </a></li>
        <li class="breadcrumb-item active shadow-lg">{{ board.name }}</li>

    </ol>
</div>
<a href="{% url 'new_topic' board.pk%}" class="btn btn-success">Add a new Topic</a>
<table class="table">
    <thead class="thead-dark">
    <tr>
        <th>Topic</th>
        <th>Created By</th>
        <th>Posts</th>
        <th>Views</th>
        <th>Created Date</th>

    </tr>
    </thead>
    <tbody>
    {% for topic in board.topics.all %}
        <tr>
        <td>{{topic.subject }}</td>
        <td>{{topic.created_by.username }}</td>
        <td>0</td>
        <td>0</td>
        <td>{{ topic.created_dt }}</td>
        </tr>

    {% endfor %}
    </tbody>
</table>


</body>
</html>